version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: uniops-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://uniops_user:uniops_secret@postgres:5432/uniops_db
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - JWT_SECRET_KEY=prod_jwt_super_secret_2026
    depends_on:
      - postgres
      - redis
      - qdrant

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: uniops-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: uniops-postgres
    environment:
      POSTGRES_USER: uniops_user
      POSTGRES_PASSWORD: uniops_secret
      POSTGRES_DB: uniops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: uniops-redis
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: uniops-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:
